name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: geodeios/geode-sdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Android
        run: geode build -p android64
      - uses: actions/upload-artifact@v4
        with:
          name: AutoBot
          path: build/*.geode
