name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Geode CLI
        run: |
          wget https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-x86_64-unknown-linux-gnu.zip
          unzip geode-cli-x86_64-unknown-linux-gnu.zip
          echo "$(pwd)" >> $GITHUB_PATH
      
      - name: Configure Geode
        run: geode configure
      
      - name: Build Mod
        run: geode build -p android64
      
      - uses: actions/upload-artifact@v4
        with:
          name: AutoBot
          path: build/*.geode
